### ISSUE TITLE
ROI Definition

### ISSUE THREAD

**Issue by SanD94** [deepneuroboun/DeepLabCut#3]
- [x] All paradigms should have ROI definitions and they should be added to config.yaml of DeepLabCut. The config file should also have the paradigm name.
- [x] Centre based analyses should have a slider to adjust the size of the centre. Also include a reset to default button (default to be defined based on the literature)

**Comment by SanD94** [comment]
@ornitorenkperry 
options in `config.yaml` file will be changed in the future for polygon definition. Sample `config.yaml` is added.

[config.yaml.zip](https://github.com/deepneuroboun/DeepLabCut/files/5364853/config.yaml.zip)

**Comment by candemircan** [comment]
slider added to change the centre size but it's not working as expected. Should figure out how the position of the bottom left corner should change without the centre of the square moving
